//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public int id { get; set; }
        public string name { get; set; }
        public int id_animal_class { get; set; }
    
        public virtual animal_class animal_class { get; set; }
    }
}
